"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from sangam.proto import sangam_pb2 as _sangam_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SchedulerServiceStub:
    """---------------------------------------------------------------------------
    Scheduler Service — accepts client requests. Bound to the client port. The
    long-lived Generate RPC parks one server pool thread per in-flight call,
    so high benchmark concurrency can fully occupy the pool. Worker callbacks
    live on SchedulerWorkerService (separate port) to avoid that starvation.
    fastdllm_serve also implements this service's Submit / Poll / Generate.
    ---------------------------------------------------------------------------
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SchedulerServiceAsyncStub: ...
    Submit: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.GenerateRequest, _sangam_pb2.SubmitResponse]
    """Submit a new generation request"""
    Poll: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.PollRequest, _sangam_pb2.PollResponse]
    """Poll for request status / results"""
    Generate: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.GenerateRequest, _sangam_pb2.GenerateResponse]
    """Blocking unary generate: server holds the call open until the request
    reaches a terminal status (COMPLETED or ERROR), then returns the final
    result. fastdllm_serve implements this; sangam returns UNIMPLEMENTED.
    """
    ExportMetrics: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.ExportMetricsRequest, _sangam_pb2.ExportMetricsResponse]
    """Export collected metrics to disk (CSVs + plots)"""
    ResetMetrics: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.ResetMetricsRequest, _sangam_pb2.ResetMetricsResponse]
    """Reset collected metrics in preparation for a fresh benchmark phase"""
    GetSchedulerStatus: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.GetSchedulerStatusRequest, _sangam_pb2.GetSchedulerStatusResponse]
    """Report scheduler worker registration state for readiness checks"""

@_typing.type_check_only
class SchedulerServiceAsyncStub(SchedulerServiceStub):
    """---------------------------------------------------------------------------
    Scheduler Service — accepts client requests. Bound to the client port. The
    long-lived Generate RPC parks one server pool thread per in-flight call,
    so high benchmark concurrency can fully occupy the pool. Worker callbacks
    live on SchedulerWorkerService (separate port) to avoid that starvation.
    fastdllm_serve also implements this service's Submit / Poll / Generate.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Submit: _aio.UnaryUnaryMultiCallable[_sangam_pb2.GenerateRequest, _sangam_pb2.SubmitResponse]  # type: ignore[assignment]
    """Submit a new generation request"""
    Poll: _aio.UnaryUnaryMultiCallable[_sangam_pb2.PollRequest, _sangam_pb2.PollResponse]  # type: ignore[assignment]
    """Poll for request status / results"""
    Generate: _aio.UnaryUnaryMultiCallable[_sangam_pb2.GenerateRequest, _sangam_pb2.GenerateResponse]  # type: ignore[assignment]
    """Blocking unary generate: server holds the call open until the request
    reaches a terminal status (COMPLETED or ERROR), then returns the final
    result. fastdllm_serve implements this; sangam returns UNIMPLEMENTED.
    """
    ExportMetrics: _aio.UnaryUnaryMultiCallable[_sangam_pb2.ExportMetricsRequest, _sangam_pb2.ExportMetricsResponse]  # type: ignore[assignment]
    """Export collected metrics to disk (CSVs + plots)"""
    ResetMetrics: _aio.UnaryUnaryMultiCallable[_sangam_pb2.ResetMetricsRequest, _sangam_pb2.ResetMetricsResponse]  # type: ignore[assignment]
    """Reset collected metrics in preparation for a fresh benchmark phase"""
    GetSchedulerStatus: _aio.UnaryUnaryMultiCallable[_sangam_pb2.GetSchedulerStatusRequest, _sangam_pb2.GetSchedulerStatusResponse]  # type: ignore[assignment]
    """Report scheduler worker registration state for readiness checks"""

class SchedulerServiceServicer(metaclass=_abc_1.ABCMeta):
    """---------------------------------------------------------------------------
    Scheduler Service — accepts client requests. Bound to the client port. The
    long-lived Generate RPC parks one server pool thread per in-flight call,
    so high benchmark concurrency can fully occupy the pool. Worker callbacks
    live on SchedulerWorkerService (separate port) to avoid that starvation.
    fastdllm_serve also implements this service's Submit / Poll / Generate.
    ---------------------------------------------------------------------------
    """

    @_abc_1.abstractmethod
    def Submit(
        self,
        request: _sangam_pb2.GenerateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.SubmitResponse, _abc.Awaitable[_sangam_pb2.SubmitResponse]]:
        """Submit a new generation request"""

    @_abc_1.abstractmethod
    def Poll(
        self,
        request: _sangam_pb2.PollRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.PollResponse, _abc.Awaitable[_sangam_pb2.PollResponse]]:
        """Poll for request status / results"""

    @_abc_1.abstractmethod
    def Generate(
        self,
        request: _sangam_pb2.GenerateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.GenerateResponse, _abc.Awaitable[_sangam_pb2.GenerateResponse]]:
        """Blocking unary generate: server holds the call open until the request
        reaches a terminal status (COMPLETED or ERROR), then returns the final
        result. fastdllm_serve implements this; sangam returns UNIMPLEMENTED.
        """

    @_abc_1.abstractmethod
    def ExportMetrics(
        self,
        request: _sangam_pb2.ExportMetricsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.ExportMetricsResponse, _abc.Awaitable[_sangam_pb2.ExportMetricsResponse]]:
        """Export collected metrics to disk (CSVs + plots)"""

    @_abc_1.abstractmethod
    def ResetMetrics(
        self,
        request: _sangam_pb2.ResetMetricsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.ResetMetricsResponse, _abc.Awaitable[_sangam_pb2.ResetMetricsResponse]]:
        """Reset collected metrics in preparation for a fresh benchmark phase"""

    @_abc_1.abstractmethod
    def GetSchedulerStatus(
        self,
        request: _sangam_pb2.GetSchedulerStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.GetSchedulerStatusResponse, _abc.Awaitable[_sangam_pb2.GetSchedulerStatusResponse]]:
        """Report scheduler worker registration state for readiness checks"""

def add_SchedulerServiceServicer_to_server(servicer: SchedulerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class SchedulerWorkerServiceStub:
    """---------------------------------------------------------------------------
    Scheduler Worker Service — bound to a separate port (scheduler_port + 1).
    Workers connect here for registration and event callbacks. Sized small
    because traffic is bounded by `num_workers × few-concurrent-RPCs`.
    ---------------------------------------------------------------------------
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SchedulerWorkerServiceAsyncStub: ...
    RegisterWorker: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.RegisterWorkerRequest, _sangam_pb2.RegisterWorkerResponse]
    """Workers call this at startup to register themselves"""
    ReportBatchMetrics: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.BatchMetricsReport, _sangam_pb2.BatchMetricsAck]
    """Workers report completed prefill/decode batches plus per-request outcomes"""
    ReportKVTransfer: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.KVTransferReport, _sangam_pb2.KVTransferAck]
    """Prefill workers report deferred KV transfer completion/failure"""

@_typing.type_check_only
class SchedulerWorkerServiceAsyncStub(SchedulerWorkerServiceStub):
    """---------------------------------------------------------------------------
    Scheduler Worker Service — bound to a separate port (scheduler_port + 1).
    Workers connect here for registration and event callbacks. Sized small
    because traffic is bounded by `num_workers × few-concurrent-RPCs`.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    RegisterWorker: _aio.UnaryUnaryMultiCallable[_sangam_pb2.RegisterWorkerRequest, _sangam_pb2.RegisterWorkerResponse]  # type: ignore[assignment]
    """Workers call this at startup to register themselves"""
    ReportBatchMetrics: _aio.UnaryUnaryMultiCallable[_sangam_pb2.BatchMetricsReport, _sangam_pb2.BatchMetricsAck]  # type: ignore[assignment]
    """Workers report completed prefill/decode batches plus per-request outcomes"""
    ReportKVTransfer: _aio.UnaryUnaryMultiCallable[_sangam_pb2.KVTransferReport, _sangam_pb2.KVTransferAck]  # type: ignore[assignment]
    """Prefill workers report deferred KV transfer completion/failure"""

class SchedulerWorkerServiceServicer(metaclass=_abc_1.ABCMeta):
    """---------------------------------------------------------------------------
    Scheduler Worker Service — bound to a separate port (scheduler_port + 1).
    Workers connect here for registration and event callbacks. Sized small
    because traffic is bounded by `num_workers × few-concurrent-RPCs`.
    ---------------------------------------------------------------------------
    """

    @_abc_1.abstractmethod
    def RegisterWorker(
        self,
        request: _sangam_pb2.RegisterWorkerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.RegisterWorkerResponse, _abc.Awaitable[_sangam_pb2.RegisterWorkerResponse]]:
        """Workers call this at startup to register themselves"""

    @_abc_1.abstractmethod
    def ReportBatchMetrics(
        self,
        request: _sangam_pb2.BatchMetricsReport,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.BatchMetricsAck, _abc.Awaitable[_sangam_pb2.BatchMetricsAck]]:
        """Workers report completed prefill/decode batches plus per-request outcomes"""

    @_abc_1.abstractmethod
    def ReportKVTransfer(
        self,
        request: _sangam_pb2.KVTransferReport,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.KVTransferAck, _abc.Awaitable[_sangam_pb2.KVTransferAck]]:
        """Prefill workers report deferred KV transfer completion/failure"""

def add_SchedulerWorkerServiceServicer_to_server(servicer: SchedulerWorkerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class PrefillWorkerServiceStub:
    """---------------------------------------------------------------------------
    Prefill Worker Service — runs forward pass, holds KV cache
    ---------------------------------------------------------------------------
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> PrefillWorkerServiceAsyncStub: ...
    EnqueuePrefill: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.EnqueuePrefillRequest, _sangam_pb2.EnqueuePrefillResponse]
    """Enqueue a prefill request (returns immediately)"""
    TriggerKVTransfer: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.TriggerKVTransferRequest, _sangam_pb2.TriggerKVTransferResponse]
    """Trigger deferred KV transfer to an assigned decode worker"""
    ReturnQueuedPrefills: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.ReturnQueuedPrefillsRequest, _sangam_pb2.ReturnQueuedPrefillsResponse]
    """Drain the waiting queue and return all unstarted requests (for work redistribution)"""

@_typing.type_check_only
class PrefillWorkerServiceAsyncStub(PrefillWorkerServiceStub):
    """---------------------------------------------------------------------------
    Prefill Worker Service — runs forward pass, holds KV cache
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    EnqueuePrefill: _aio.UnaryUnaryMultiCallable[_sangam_pb2.EnqueuePrefillRequest, _sangam_pb2.EnqueuePrefillResponse]  # type: ignore[assignment]
    """Enqueue a prefill request (returns immediately)"""
    TriggerKVTransfer: _aio.UnaryUnaryMultiCallable[_sangam_pb2.TriggerKVTransferRequest, _sangam_pb2.TriggerKVTransferResponse]  # type: ignore[assignment]
    """Trigger deferred KV transfer to an assigned decode worker"""
    ReturnQueuedPrefills: _aio.UnaryUnaryMultiCallable[_sangam_pb2.ReturnQueuedPrefillsRequest, _sangam_pb2.ReturnQueuedPrefillsResponse]  # type: ignore[assignment]
    """Drain the waiting queue and return all unstarted requests (for work redistribution)"""

class PrefillWorkerServiceServicer(metaclass=_abc_1.ABCMeta):
    """---------------------------------------------------------------------------
    Prefill Worker Service — runs forward pass, holds KV cache
    ---------------------------------------------------------------------------
    """

    @_abc_1.abstractmethod
    def EnqueuePrefill(
        self,
        request: _sangam_pb2.EnqueuePrefillRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.EnqueuePrefillResponse, _abc.Awaitable[_sangam_pb2.EnqueuePrefillResponse]]:
        """Enqueue a prefill request (returns immediately)"""

    @_abc_1.abstractmethod
    def TriggerKVTransfer(
        self,
        request: _sangam_pb2.TriggerKVTransferRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.TriggerKVTransferResponse, _abc.Awaitable[_sangam_pb2.TriggerKVTransferResponse]]:
        """Trigger deferred KV transfer to an assigned decode worker"""

    @_abc_1.abstractmethod
    def ReturnQueuedPrefills(
        self,
        request: _sangam_pb2.ReturnQueuedPrefillsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.ReturnQueuedPrefillsResponse, _abc.Awaitable[_sangam_pb2.ReturnQueuedPrefillsResponse]]:
        """Drain the waiting queue and return all unstarted requests (for work redistribution)"""

def add_PrefillWorkerServiceServicer_to_server(servicer: PrefillWorkerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class DecodeWorkerServiceStub:
    """---------------------------------------------------------------------------
    Decode Worker Service — receives KV cache, runs iterative decoding
    ---------------------------------------------------------------------------
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DecodeWorkerServiceAsyncStub: ...
    ReceiveKVCache: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.ReceiveKVCacheRequest, _sangam_pb2.ReceiveKVCacheResponse]
    """Receive KV cache from prefill worker via NCCL"""
    EnqueueDecode: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.EnqueueDecodeRequest, _sangam_pb2.EnqueueDecodeResponse]
    """Enqueue a decode request (returns immediately)"""
    FreeDecodeState: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.FreeDecodeStateRequest, _sangam_pb2.FreeDecodeStateResponse]
    """Free stored KV cache and state for a request"""

@_typing.type_check_only
class DecodeWorkerServiceAsyncStub(DecodeWorkerServiceStub):
    """---------------------------------------------------------------------------
    Decode Worker Service — receives KV cache, runs iterative decoding
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ReceiveKVCache: _aio.UnaryUnaryMultiCallable[_sangam_pb2.ReceiveKVCacheRequest, _sangam_pb2.ReceiveKVCacheResponse]  # type: ignore[assignment]
    """Receive KV cache from prefill worker via NCCL"""
    EnqueueDecode: _aio.UnaryUnaryMultiCallable[_sangam_pb2.EnqueueDecodeRequest, _sangam_pb2.EnqueueDecodeResponse]  # type: ignore[assignment]
    """Enqueue a decode request (returns immediately)"""
    FreeDecodeState: _aio.UnaryUnaryMultiCallable[_sangam_pb2.FreeDecodeStateRequest, _sangam_pb2.FreeDecodeStateResponse]  # type: ignore[assignment]
    """Free stored KV cache and state for a request"""

class DecodeWorkerServiceServicer(metaclass=_abc_1.ABCMeta):
    """---------------------------------------------------------------------------
    Decode Worker Service — receives KV cache, runs iterative decoding
    ---------------------------------------------------------------------------
    """

    @_abc_1.abstractmethod
    def ReceiveKVCache(
        self,
        request: _sangam_pb2.ReceiveKVCacheRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.ReceiveKVCacheResponse, _abc.Awaitable[_sangam_pb2.ReceiveKVCacheResponse]]:
        """Receive KV cache from prefill worker via NCCL"""

    @_abc_1.abstractmethod
    def EnqueueDecode(
        self,
        request: _sangam_pb2.EnqueueDecodeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.EnqueueDecodeResponse, _abc.Awaitable[_sangam_pb2.EnqueueDecodeResponse]]:
        """Enqueue a decode request (returns immediately)"""

    @_abc_1.abstractmethod
    def FreeDecodeState(
        self,
        request: _sangam_pb2.FreeDecodeStateRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.FreeDecodeStateResponse, _abc.Awaitable[_sangam_pb2.FreeDecodeStateResponse]]:
        """Free stored KV cache and state for a request"""

def add_DecodeWorkerServiceServicer_to_server(servicer: DecodeWorkerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class WorkerManagementServiceStub:
    """---------------------------------------------------------------------------
    Worker Management Service — lifecycle operations for dynamic workers
    ---------------------------------------------------------------------------
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> WorkerManagementServiceAsyncStub: ...
    ConvertPhase: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.ConvertPhaseRequest, _sangam_pb2.ConvertPhaseResponse]
    """Convert an in-process worker between prefill and decode roles"""

@_typing.type_check_only
class WorkerManagementServiceAsyncStub(WorkerManagementServiceStub):
    """---------------------------------------------------------------------------
    Worker Management Service — lifecycle operations for dynamic workers
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ConvertPhase: _aio.UnaryUnaryMultiCallable[_sangam_pb2.ConvertPhaseRequest, _sangam_pb2.ConvertPhaseResponse]  # type: ignore[assignment]
    """Convert an in-process worker between prefill and decode roles"""

class WorkerManagementServiceServicer(metaclass=_abc_1.ABCMeta):
    """---------------------------------------------------------------------------
    Worker Management Service — lifecycle operations for dynamic workers
    ---------------------------------------------------------------------------
    """

    @_abc_1.abstractmethod
    def ConvertPhase(
        self,
        request: _sangam_pb2.ConvertPhaseRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.ConvertPhaseResponse, _abc.Awaitable[_sangam_pb2.ConvertPhaseResponse]]:
        """Convert an in-process worker between prefill and decode roles"""

def add_WorkerManagementServiceServicer_to_server(servicer: WorkerManagementServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class ColocatedWorkerServiceStub:
    """---------------------------------------------------------------------------
    Colocated Worker Service — does both prefill and decode on same GPU
    ---------------------------------------------------------------------------
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ColocatedWorkerServiceAsyncStub: ...
    EnqueueRequest: _grpc.UnaryUnaryMultiCallable[_sangam_pb2.EnqueueColocatedRequest, _sangam_pb2.EnqueueColocatedResponse]
    """Enqueue a request for prefill + decode (returns immediately)"""

@_typing.type_check_only
class ColocatedWorkerServiceAsyncStub(ColocatedWorkerServiceStub):
    """---------------------------------------------------------------------------
    Colocated Worker Service — does both prefill and decode on same GPU
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    EnqueueRequest: _aio.UnaryUnaryMultiCallable[_sangam_pb2.EnqueueColocatedRequest, _sangam_pb2.EnqueueColocatedResponse]  # type: ignore[assignment]
    """Enqueue a request for prefill + decode (returns immediately)"""

class ColocatedWorkerServiceServicer(metaclass=_abc_1.ABCMeta):
    """---------------------------------------------------------------------------
    Colocated Worker Service — does both prefill and decode on same GPU
    ---------------------------------------------------------------------------
    """

    @_abc_1.abstractmethod
    def EnqueueRequest(
        self,
        request: _sangam_pb2.EnqueueColocatedRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_sangam_pb2.EnqueueColocatedResponse, _abc.Awaitable[_sangam_pb2.EnqueueColocatedResponse]]:
        """Enqueue a request for prefill + decode (returns immediately)"""

def add_ColocatedWorkerServiceServicer_to_server(servicer: ColocatedWorkerServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
