# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sangam.proto import sangam_pb2 as sangam__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sangam_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """---------------------------------------------------------------------------
    Scheduler Service — accepts client requests. Bound to the client port. The
    long-lived Generate RPC parks one server pool thread per in-flight call,
    so high benchmark concurrency can fully occupy the pool. Worker callbacks
    live on SchedulerWorkerService (separate port) to avoid that starvation.
    fastdllm_serve also implements this service's Submit / Poll / Generate.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/sangam.SchedulerService/Submit',
                request_serializer=sangam__pb2.GenerateRequest.SerializeToString,
                response_deserializer=sangam__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.Poll = channel.unary_unary(
                '/sangam.SchedulerService/Poll',
                request_serializer=sangam__pb2.PollRequest.SerializeToString,
                response_deserializer=sangam__pb2.PollResponse.FromString,
                _registered_method=True)
        self.Generate = channel.unary_unary(
                '/sangam.SchedulerService/Generate',
                request_serializer=sangam__pb2.GenerateRequest.SerializeToString,
                response_deserializer=sangam__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.ExportMetrics = channel.unary_unary(
                '/sangam.SchedulerService/ExportMetrics',
                request_serializer=sangam__pb2.ExportMetricsRequest.SerializeToString,
                response_deserializer=sangam__pb2.ExportMetricsResponse.FromString,
                _registered_method=True)
        self.ResetMetrics = channel.unary_unary(
                '/sangam.SchedulerService/ResetMetrics',
                request_serializer=sangam__pb2.ResetMetricsRequest.SerializeToString,
                response_deserializer=sangam__pb2.ResetMetricsResponse.FromString,
                _registered_method=True)
        self.GetSchedulerStatus = channel.unary_unary(
                '/sangam.SchedulerService/GetSchedulerStatus',
                request_serializer=sangam__pb2.GetSchedulerStatusRequest.SerializeToString,
                response_deserializer=sangam__pb2.GetSchedulerStatusResponse.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """---------------------------------------------------------------------------
    Scheduler Service — accepts client requests. Bound to the client port. The
    long-lived Generate RPC parks one server pool thread per in-flight call,
    so high benchmark concurrency can fully occupy the pool. Worker callbacks
    live on SchedulerWorkerService (separate port) to avoid that starvation.
    fastdllm_serve also implements this service's Submit / Poll / Generate.
    ---------------------------------------------------------------------------
    """

    def Submit(self, request, context):
        """Submit a new generation request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Poll(self, request, context):
        """Poll for request status / results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Blocking unary generate: server holds the call open until the request
        reaches a terminal status (COMPLETED or ERROR), then returns the final
        result. fastdllm_serve implements this; sangam returns UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportMetrics(self, request, context):
        """Export collected metrics to disk (CSVs + plots)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetMetrics(self, request, context):
        """Reset collected metrics in preparation for a fresh benchmark phase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedulerStatus(self, request, context):
        """Report scheduler worker registration state for readiness checks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=sangam__pb2.GenerateRequest.FromString,
                    response_serializer=sangam__pb2.SubmitResponse.SerializeToString,
            ),
            'Poll': grpc.unary_unary_rpc_method_handler(
                    servicer.Poll,
                    request_deserializer=sangam__pb2.PollRequest.FromString,
                    response_serializer=sangam__pb2.PollResponse.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=sangam__pb2.GenerateRequest.FromString,
                    response_serializer=sangam__pb2.GenerateResponse.SerializeToString,
            ),
            'ExportMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportMetrics,
                    request_deserializer=sangam__pb2.ExportMetricsRequest.FromString,
                    response_serializer=sangam__pb2.ExportMetricsResponse.SerializeToString,
            ),
            'ResetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetMetrics,
                    request_deserializer=sangam__pb2.ResetMetricsRequest.FromString,
                    response_serializer=sangam__pb2.ResetMetricsResponse.SerializeToString,
            ),
            'GetSchedulerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedulerStatus,
                    request_deserializer=sangam__pb2.GetSchedulerStatusRequest.FromString,
                    response_serializer=sangam__pb2.GetSchedulerStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sangam.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sangam.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """---------------------------------------------------------------------------
    Scheduler Service — accepts client requests. Bound to the client port. The
    long-lived Generate RPC parks one server pool thread per in-flight call,
    so high benchmark concurrency can fully occupy the pool. Worker callbacks
    live on SchedulerWorkerService (separate port) to avoid that starvation.
    fastdllm_serve also implements this service's Submit / Poll / Generate.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.SchedulerService/Submit',
            sangam__pb2.GenerateRequest.SerializeToString,
            sangam__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Poll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.SchedulerService/Poll',
            sangam__pb2.PollRequest.SerializeToString,
            sangam__pb2.PollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.SchedulerService/Generate',
            sangam__pb2.GenerateRequest.SerializeToString,
            sangam__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.SchedulerService/ExportMetrics',
            sangam__pb2.ExportMetricsRequest.SerializeToString,
            sangam__pb2.ExportMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.SchedulerService/ResetMetrics',
            sangam__pb2.ResetMetricsRequest.SerializeToString,
            sangam__pb2.ResetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedulerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.SchedulerService/GetSchedulerStatus',
            sangam__pb2.GetSchedulerStatusRequest.SerializeToString,
            sangam__pb2.GetSchedulerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SchedulerWorkerServiceStub(object):
    """---------------------------------------------------------------------------
    Scheduler Worker Service — bound to a separate port (scheduler_port + 1).
    Workers connect here for registration and event callbacks. Sized small
    because traffic is bounded by `num_workers × few-concurrent-RPCs`.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/sangam.SchedulerWorkerService/RegisterWorker',
                request_serializer=sangam__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=sangam__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.ReportBatchMetrics = channel.unary_unary(
                '/sangam.SchedulerWorkerService/ReportBatchMetrics',
                request_serializer=sangam__pb2.BatchMetricsReport.SerializeToString,
                response_deserializer=sangam__pb2.BatchMetricsAck.FromString,
                _registered_method=True)
        self.ReportKVTransfer = channel.unary_unary(
                '/sangam.SchedulerWorkerService/ReportKVTransfer',
                request_serializer=sangam__pb2.KVTransferReport.SerializeToString,
                response_deserializer=sangam__pb2.KVTransferAck.FromString,
                _registered_method=True)


class SchedulerWorkerServiceServicer(object):
    """---------------------------------------------------------------------------
    Scheduler Worker Service — bound to a separate port (scheduler_port + 1).
    Workers connect here for registration and event callbacks. Sized small
    because traffic is bounded by `num_workers × few-concurrent-RPCs`.
    ---------------------------------------------------------------------------
    """

    def RegisterWorker(self, request, context):
        """Workers call this at startup to register themselves
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportBatchMetrics(self, request, context):
        """Workers report completed prefill/decode batches plus per-request outcomes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportKVTransfer(self, request, context):
        """Prefill workers report deferred KV transfer completion/failure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=sangam__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=sangam__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'ReportBatchMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportBatchMetrics,
                    request_deserializer=sangam__pb2.BatchMetricsReport.FromString,
                    response_serializer=sangam__pb2.BatchMetricsAck.SerializeToString,
            ),
            'ReportKVTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportKVTransfer,
                    request_deserializer=sangam__pb2.KVTransferReport.FromString,
                    response_serializer=sangam__pb2.KVTransferAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sangam.SchedulerWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sangam.SchedulerWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerWorkerService(object):
    """---------------------------------------------------------------------------
    Scheduler Worker Service — bound to a separate port (scheduler_port + 1).
    Workers connect here for registration and event callbacks. Sized small
    because traffic is bounded by `num_workers × few-concurrent-RPCs`.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.SchedulerWorkerService/RegisterWorker',
            sangam__pb2.RegisterWorkerRequest.SerializeToString,
            sangam__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportBatchMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.SchedulerWorkerService/ReportBatchMetrics',
            sangam__pb2.BatchMetricsReport.SerializeToString,
            sangam__pb2.BatchMetricsAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportKVTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.SchedulerWorkerService/ReportKVTransfer',
            sangam__pb2.KVTransferReport.SerializeToString,
            sangam__pb2.KVTransferAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PrefillWorkerServiceStub(object):
    """---------------------------------------------------------------------------
    Prefill Worker Service — runs forward pass, holds KV cache
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueuePrefill = channel.unary_unary(
                '/sangam.PrefillWorkerService/EnqueuePrefill',
                request_serializer=sangam__pb2.EnqueuePrefillRequest.SerializeToString,
                response_deserializer=sangam__pb2.EnqueuePrefillResponse.FromString,
                _registered_method=True)
        self.TriggerKVTransfer = channel.unary_unary(
                '/sangam.PrefillWorkerService/TriggerKVTransfer',
                request_serializer=sangam__pb2.TriggerKVTransferRequest.SerializeToString,
                response_deserializer=sangam__pb2.TriggerKVTransferResponse.FromString,
                _registered_method=True)
        self.ReturnQueuedPrefills = channel.unary_unary(
                '/sangam.PrefillWorkerService/ReturnQueuedPrefills',
                request_serializer=sangam__pb2.ReturnQueuedPrefillsRequest.SerializeToString,
                response_deserializer=sangam__pb2.ReturnQueuedPrefillsResponse.FromString,
                _registered_method=True)


class PrefillWorkerServiceServicer(object):
    """---------------------------------------------------------------------------
    Prefill Worker Service — runs forward pass, holds KV cache
    ---------------------------------------------------------------------------
    """

    def EnqueuePrefill(self, request, context):
        """Enqueue a prefill request (returns immediately)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerKVTransfer(self, request, context):
        """Trigger deferred KV transfer to an assigned decode worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnQueuedPrefills(self, request, context):
        """Drain the waiting queue and return all unstarted requests (for work redistribution)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrefillWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueuePrefill': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueuePrefill,
                    request_deserializer=sangam__pb2.EnqueuePrefillRequest.FromString,
                    response_serializer=sangam__pb2.EnqueuePrefillResponse.SerializeToString,
            ),
            'TriggerKVTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerKVTransfer,
                    request_deserializer=sangam__pb2.TriggerKVTransferRequest.FromString,
                    response_serializer=sangam__pb2.TriggerKVTransferResponse.SerializeToString,
            ),
            'ReturnQueuedPrefills': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnQueuedPrefills,
                    request_deserializer=sangam__pb2.ReturnQueuedPrefillsRequest.FromString,
                    response_serializer=sangam__pb2.ReturnQueuedPrefillsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sangam.PrefillWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sangam.PrefillWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrefillWorkerService(object):
    """---------------------------------------------------------------------------
    Prefill Worker Service — runs forward pass, holds KV cache
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def EnqueuePrefill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.PrefillWorkerService/EnqueuePrefill',
            sangam__pb2.EnqueuePrefillRequest.SerializeToString,
            sangam__pb2.EnqueuePrefillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerKVTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.PrefillWorkerService/TriggerKVTransfer',
            sangam__pb2.TriggerKVTransferRequest.SerializeToString,
            sangam__pb2.TriggerKVTransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnQueuedPrefills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.PrefillWorkerService/ReturnQueuedPrefills',
            sangam__pb2.ReturnQueuedPrefillsRequest.SerializeToString,
            sangam__pb2.ReturnQueuedPrefillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DecodeWorkerServiceStub(object):
    """---------------------------------------------------------------------------
    Decode Worker Service — receives KV cache, runs iterative decoding
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveKVCache = channel.unary_unary(
                '/sangam.DecodeWorkerService/ReceiveKVCache',
                request_serializer=sangam__pb2.ReceiveKVCacheRequest.SerializeToString,
                response_deserializer=sangam__pb2.ReceiveKVCacheResponse.FromString,
                _registered_method=True)
        self.EnqueueDecode = channel.unary_unary(
                '/sangam.DecodeWorkerService/EnqueueDecode',
                request_serializer=sangam__pb2.EnqueueDecodeRequest.SerializeToString,
                response_deserializer=sangam__pb2.EnqueueDecodeResponse.FromString,
                _registered_method=True)
        self.FreeDecodeState = channel.unary_unary(
                '/sangam.DecodeWorkerService/FreeDecodeState',
                request_serializer=sangam__pb2.FreeDecodeStateRequest.SerializeToString,
                response_deserializer=sangam__pb2.FreeDecodeStateResponse.FromString,
                _registered_method=True)


class DecodeWorkerServiceServicer(object):
    """---------------------------------------------------------------------------
    Decode Worker Service — receives KV cache, runs iterative decoding
    ---------------------------------------------------------------------------
    """

    def ReceiveKVCache(self, request, context):
        """Receive KV cache from prefill worker via NCCL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueDecode(self, request, context):
        """Enqueue a decode request (returns immediately)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FreeDecodeState(self, request, context):
        """Free stored KV cache and state for a request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecodeWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveKVCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveKVCache,
                    request_deserializer=sangam__pb2.ReceiveKVCacheRequest.FromString,
                    response_serializer=sangam__pb2.ReceiveKVCacheResponse.SerializeToString,
            ),
            'EnqueueDecode': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueDecode,
                    request_deserializer=sangam__pb2.EnqueueDecodeRequest.FromString,
                    response_serializer=sangam__pb2.EnqueueDecodeResponse.SerializeToString,
            ),
            'FreeDecodeState': grpc.unary_unary_rpc_method_handler(
                    servicer.FreeDecodeState,
                    request_deserializer=sangam__pb2.FreeDecodeStateRequest.FromString,
                    response_serializer=sangam__pb2.FreeDecodeStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sangam.DecodeWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sangam.DecodeWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecodeWorkerService(object):
    """---------------------------------------------------------------------------
    Decode Worker Service — receives KV cache, runs iterative decoding
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def ReceiveKVCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.DecodeWorkerService/ReceiveKVCache',
            sangam__pb2.ReceiveKVCacheRequest.SerializeToString,
            sangam__pb2.ReceiveKVCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueDecode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.DecodeWorkerService/EnqueueDecode',
            sangam__pb2.EnqueueDecodeRequest.SerializeToString,
            sangam__pb2.EnqueueDecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FreeDecodeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.DecodeWorkerService/FreeDecodeState',
            sangam__pb2.FreeDecodeStateRequest.SerializeToString,
            sangam__pb2.FreeDecodeStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerManagementServiceStub(object):
    """---------------------------------------------------------------------------
    Worker Management Service — lifecycle operations for dynamic workers
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertPhase = channel.unary_unary(
                '/sangam.WorkerManagementService/ConvertPhase',
                request_serializer=sangam__pb2.ConvertPhaseRequest.SerializeToString,
                response_deserializer=sangam__pb2.ConvertPhaseResponse.FromString,
                _registered_method=True)


class WorkerManagementServiceServicer(object):
    """---------------------------------------------------------------------------
    Worker Management Service — lifecycle operations for dynamic workers
    ---------------------------------------------------------------------------
    """

    def ConvertPhase(self, request, context):
        """Convert an in-process worker between prefill and decode roles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertPhase': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertPhase,
                    request_deserializer=sangam__pb2.ConvertPhaseRequest.FromString,
                    response_serializer=sangam__pb2.ConvertPhaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sangam.WorkerManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sangam.WorkerManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerManagementService(object):
    """---------------------------------------------------------------------------
    Worker Management Service — lifecycle operations for dynamic workers
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def ConvertPhase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.WorkerManagementService/ConvertPhase',
            sangam__pb2.ConvertPhaseRequest.SerializeToString,
            sangam__pb2.ConvertPhaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ColocatedWorkerServiceStub(object):
    """---------------------------------------------------------------------------
    Colocated Worker Service — does both prefill and decode on same GPU
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueRequest = channel.unary_unary(
                '/sangam.ColocatedWorkerService/EnqueueRequest',
                request_serializer=sangam__pb2.EnqueueColocatedRequest.SerializeToString,
                response_deserializer=sangam__pb2.EnqueueColocatedResponse.FromString,
                _registered_method=True)


class ColocatedWorkerServiceServicer(object):
    """---------------------------------------------------------------------------
    Colocated Worker Service — does both prefill and decode on same GPU
    ---------------------------------------------------------------------------
    """

    def EnqueueRequest(self, request, context):
        """Enqueue a request for prefill + decode (returns immediately)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ColocatedWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueRequest,
                    request_deserializer=sangam__pb2.EnqueueColocatedRequest.FromString,
                    response_serializer=sangam__pb2.EnqueueColocatedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sangam.ColocatedWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sangam.ColocatedWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ColocatedWorkerService(object):
    """---------------------------------------------------------------------------
    Colocated Worker Service — does both prefill and decode on same GPU
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def EnqueueRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sangam.ColocatedWorkerService/EnqueueRequest',
            sangam__pb2.EnqueueColocatedRequest.SerializeToString,
            sangam__pb2.EnqueueColocatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
